comment:
  layout: "diff, flags, files"
coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 5%
        only_pulls: true
    patch:
      default:
        target: 80%
        only_pulls: true

#coverage:
#  status:
#    project:
#      default:
#        # basic
#        target: auto
#        threshold: 0%
#        base: auto
#        flags:
#          - unit
#        paths:
#          - "src"
#        # advanced settings
#        branches:
#          - coverage
#        if_ci_failed: error #success, failure, error, ignore
#        informational: false
#        only_pulls: false