name: MANUALLY PIPELINE

on:
  issue_comment:
    types:
      - created
      - edited

    branches:
      - 'branch*'
      - thirdparty_branch

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'

concurrency:
  group: ${{ github.event.number }}-MANUALLY
  cancel-in-progress: true

permissions:
  checks: write
  actions: write
  contents: write
  deployments: write
  discussions: write
  issues: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  Test:
    runs-on: self-hosted
    if: ${{ github.event.issue.pull_request }}
    env:
      PR_NUMBER: ${{ github.event.issue.number }}
    steps:
      - run: |
          set -x
          echo ${{ github.event.issue.number }}
          echo ${GITHUB_SHA}
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          echo $git_hash
          echo ${{ github.sha }}


        

#    deploy:
#      runs-on: self-hosted
#      if: always() && needs.build.result == 'success'
#      needs: build
#      name: DEPLOY SR
#      env:
#        PR_NUMBER: ${{ github.event.number }}
#        CLUSTER_NAME: admit-default
#      outputs:
#        fe: ${{steps.deploy_sr.outputs.fe}}
#        be: ${{steps.deploy_sr.outputs.be}}
#      steps:
#        - name: Clean Workspace
#          uses: AutoModality/action-clean@v1.1.0
#
#        - name: BRANCH INFO
#          id: branch
#          run: |
#            echo ${{github.base_ref}}
#            echo "branch=${{github.base_ref}}" >> $GITHUB_OUTPUT
#
#        - name: Apply for resources
#          id: apply_resource
#          run: |
#            set -x
#            rm -rf ./elastic-service
#            cp -rf /var/lib/elastic-service ./elastic-service
#            cd elastic-service && git pull
#            ./bin/elastic-cluster.sh --template admit-default
#            cp conf/starrocks_deploy.conf /var/lib/elastic-service/conf/starrocks_deploy.conf
#
#        - name: Deploy SR
#          id: deploy_sr
#          run: |
#            set -x
#            cd elastic-service
#            ./bin/deploy-cluster.sh -c ${CLUSTER_NAME} --output oss://starrocks-ci-release/${{steps.branch.outputs.branch}}/Release/pr/${{needs.build.outputs.build_output_tar}}
#
#        - run: |
#            echo "FE: ${{steps.deploy_sr.outputs.fe}}, BE: ${{steps.deploy_sr.outputs.be}}"
#
#      admit:
#        runs-on: self-hosted
#        name: ADMIT TEST
#        needs: deploy
#        if: always() && needs.deploy.result == 'success'
#        timeout-minutes: 60
#        env:
#          PR_NUMBER: ${{ github.event.number }}
#          CLUSTER_NAME: admit-default
#          FE_NODE: ${{ needs.deploy.outputs.fe }}
#          BE_NODE: ${{ needs.deploy.outputs.be }}
#        steps:
#          - name: Clean Workspace
#            uses: AutoModality/action-clean@v1.1.0
#
#          - name: Run Case
#            run: |
#              set -x
#              echo "FE: ${{needs.deploy.outputs.fe}}, BE: ${{needs.deploy.outputs.be}}"
#
#              cd ${{ github.workspace }}
#              rm -rf ./elastic-service
#              ln -s /var/lib/elastic-service ./elastic-service
#              cd elastic-service && git pull
#
#              cd ${{ github.workspace }}
#              rm -rf ./StarRocksTest && cp -rf /var/lib/StarRocksTest ./StarRocksTest
#              cd ./StarRocksTest && git pull
#
#              cd ${{ github.workspace }}/elastic-service
#              ./bin/run-admit.sh
#
#          - name: Publish Test Results
#            uses: mikepenz/action-junit-report@v3
#            if: success() || failure()
#            with:
#              check_name: 'Admit Test Results'
#              detailed_summary: true
#              token: ${{ secrets.GITHUB_TOKEN }}
#              report_paths: 'StarRocksTest/result/*.xml'