name: REGRESSION PIPELINE

on:
  issue_comment:
    types:
      - created
      - edited

    branches:
      - 'branch*'
      - thirdparty_branch

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'

concurrency:
  group: ${{ github.event.number }}-MANUALLY
  cancel-in-progress: true

permissions:
  checks: write
  actions: write
  contents: write
  deployments: write
  discussions: write
  issues: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  jenkins:
    name: jenkins
    runs-on: self-hosted
    steps:
      - name: trigger single Job
        uses: mickeygoussetorg/trigger-jenkins-job@v1
        with:
          jenkins-server: "http://39.101.206.100:8090"
          jenkins-job: "test"
          jenkins-username: "starrocks"
          jenkins-pat: ${{ secrets.JENKINS_TOKEN }}
          poll-time: 10
          timeout-value: 360
          verbose: true

#  init:
#    name: INIT
#    runs-on: self-hosted
#    if: >
#      github.event.issue.pull_request &&
#      contains(github.event.comment.body, 'run regression')
#    outputs:
#      SHA: ${{ steps.check_tar.outputs.SHA }}
#      TAR_PATH: ${{ steps.check_tar.outputs.TAR_PATH }}
#      REF: ${{ steps.info.outputs.ref }}
#    steps:
#      - name: COMMIT INFO
#        id: info
#        run: |
#          set -eo pipefail
#          sha=`curl -L \
#            -H "Accept: application/vnd.github+json" \
#            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
#            -H "X-GitHub-Api-Version: 2022-11-28" \
#            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.issue.number }} 2>/dev/null \
#            | jq .head.sha`
#          echo "sha=${sha//\"}" >> $GITHUB_OUTPUT
#
#          ref=`curl -L \
#            -H "Accept: application/vnd.github+json" \
#            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
#            -H "X-GitHub-Api-Version: 2022-11-28" \
#            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.issue.number }} 2>/dev/null \
#            | jq .base.ref`
#          echo "ref=${ref//\"}" >> $GITHUB_OUTPUT
#
#      - name: Check TAR
#        id: check_tar
#        env:
#          NUMBER: ${{ github.event.issue.number }}
#          SHA: ${{ steps.info.outputs.sha }}
#          BRANCH: ${{ steps.info.outputs.ref }}
#        run: |
#          set -eo pipefail
#          SHA=${SHA::7}
#          cd /var/local/env
#          build_output_tar=oss://starrocks-ci-release/${BRANCH}/Release/pr/starrocks-${SHA}.tar.gz
#          ./ossutil64 --config-file .ossutilconfig ls ${build_output_tar}  | grep tar.gz | head -n 1 \
#            || (echo "Empty tar file, please wait for the build job to be success.." && exit -1)
#          echo "SHA=${SHA}" >> $GITHUB_OUTPUT
#          echo "TAR_PATH=${build_output_tar}" >> $GITHUB_OUTPUT

#  Deploy SR:
#    runs-on: self-hosted
#    needs: [init]
#    env:
#      PR_NUMBER: ${{ github.event.issue.number }}
#      SHA: ${{ needs.init.outputs.SHA }}
#      BRANCH: ${{ needs.init.outputs.REF }}
#      TAR_PATH: ${{ needs.init.outputs.TAR_PATH }}
#      CLUSTER_NAME: daily-default
#    outputs:
#      fe: ${{steps.deploy_sr.outputs.fe}}
#      be: ${{steps.deploy_sr.outputs.be}}
#    steps:
#      - name: Clean Workspace
#        run: rm -rf ${{ github.workspace }}/*
#
#      - name: Apply for resources
#        id: apply_resource
#        run: |
#          set -x
#          rm -rf ./elastic-service
#          cp -rf /var/lib/elastic-service ./elastic-service
#          cd elastic-service && git pull
#          ./bin/elastic-cluster.sh --template admit-default
#          cp conf/starrocks_deploy.conf /var/lib/elastic-service/conf/starrocks_deploy.conf
#
#      - name: Deploy SR
#        id: deploy_sr
#        run: |
#          set -x
#          cd elastic-service
#          ./bin/deploy-cluster.sh -c ${CLUSTER_NAME} --output ${TAR_PATH}
#
#      - run: |
#          echo "FE: ${{steps.deploy_sr.outputs.fe}}, BE: ${{steps.deploy_sr.outputs.be}}"

#      admit:
#        runs-on: self-hosted
#        name: ADMIT TEST
#        needs: deploy
#        if: always() && needs.deploy.result == 'success'
#        timeout-minutes: 60
#        env:
#          PR_NUMBER: ${{ github.event.number }}
#          CLUSTER_NAME: admit-default
#          FE_NODE: ${{ needs.deploy.outputs.fe }}
#          BE_NODE: ${{ needs.deploy.outputs.be }}
#        steps:
#          - name: Clean Workspace
#            uses: AutoModality/action-clean@v1.1.0
#
#          - name: Run Case
#            run: |
#              set -x
#              echo "FE: ${{needs.deploy.outputs.fe}}, BE: ${{needs.deploy.outputs.be}}"
#
#              cd ${{ github.workspace }}
#              rm -rf ./elastic-service
#              ln -s /var/lib/elastic-service ./elastic-service
#              cd elastic-service && git pull
#
#              cd ${{ github.workspace }}
#              rm -rf ./StarRocksTest && cp -rf /var/lib/StarRocksTest ./StarRocksTest
#              cd ./StarRocksTest && git pull
#
#              cd ${{ github.workspace }}/elastic-service
#              ./bin/run-admit.sh
#
#          - name: Publish Test Results
#            uses: mikepenz/action-junit-report@v3
#            if: success() || failure()
#            with:
#              check_name: 'Admit Test Results'
#              detailed_summary: true
#              token: ${{ secrets.GITHUB_TOKEN }}
#              report_paths: 'StarRocksTest/result/*.xml'