name: CI PIPELINE

on:
  pull_request_target:
    types:
      - opened
      - synchronize

    branches:
      - main

concurrency:
  group: ${{ github.event.number }}
  cancel-in-progress: true

permissions:
  checks: write
  actions: write
  contents: write
  deployments: write
  discussions: write
  issues: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  doc-checker:
    runs-on: ubuntu-latest
    name: DOC FILTER
    outputs:
      output1: ${{ steps.doc-changes-info.outputs.doc }}
    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            doc:
            - 'docs/**'
      - name: DOC CHECK INFO
        id: doc-changes-info
        run: |
          echo "doc=${{ steps.changes.outputs.doc }}" >> $GITHUB_OUTPUT

  be-checker:
    runs-on: ubuntu-latest
    name: BE FILTER
    outputs:
      output1: ${{ steps.be-changes-info.outputs.be }}
    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            be:
            - 'be/**'
            - 'gensrc/**'
            - 'run-be-ut.sh'
            - 'build.sh'

      - name: BE CHECK INFO
        id: be-changes-info
        run: |
          echo "be=${{ steps.changes.outputs.be }}" >> $GITHUB_OUTPUT

  be-ut:
    runs-on: self-hosted
    needs: [ be-checker ]
    timeout-minutes: 90
    name: BE UT
    env:
      PR_NUMBER: ${{ github.event.number }}
    steps:
      - name: BRANCH INFO
        id: branch
        run: |
          echo ${{github.base_ref}}
          echo "branch=${{github.base_ref}}" >> $GITHUB_OUTPUT

#      - name: UPDATE ECI & RUN UT
#        id: run_ut
#        shell: bash
#        timeout-minutes: 90
#        run: |
#          set -ex
#          rm -rf ./elastic-service
#          ln -s /var/lib/elastic-service ./elastic-service
#          cd elastic-service && git pull
#          ./bin/elastic-ut.sh --pr ${PR_NUMBER} --module be
#
#      - name: clean ECI
#        if: always()
#        run: |
#          echo ${{ steps.run_ut.outputs.ECI_ID }}
#          eci rm ${{ steps.run_ut.outputs.ECI_ID }}
#
#      - name: Upload log
#        uses: actions/upload-artifact@v3
#        if: always()
#        with:
#          name: BE UT LOG
#          path: ${{ steps.run_ut.outputs.RES_LOG }}
#          retention-days: 1
#
#      - name: Clean ENV
#        if: always()
#        run: |
#          rm -f ${{ steps.run_ut.outputs.RES_FILE }}
#          rm -f ${{ steps.run_ut.outputs.RES_LOG }}

  fe-checker:
    runs-on: ubuntu-latest
    name: FE FILTER
    outputs:
      output1: ${{ steps.fe-changes-info.outputs.fe }}
    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            fe:
              - 'fe/**'
              - 'gensrc/**'
              - 'run-fe-ut.sh'
              - 'java-extensions/**'
              - 'build.sh'

      - run: echo ${{ steps.changes.outputs.fe }}

      - name: FE CHECK INFO
        id: fe-changes-info
        run: |
          echo "fe=${{ steps.changes.outputs.fe }}" >> $GITHUB_OUTPUT

  fe-ut:
    runs-on: [self-hosted]
    needs: fe-checker
    name: FE UT
    env:
      PR_NUMBER: ${{ github.event.number }}
    steps:
      - name: Clean Workspace
        uses: AutoModality/action-clean@v1.1.0

      - name: BRANCH INFO
        id: branch
        run: |
          echo ${{github.base_ref}}
          echo "branch=${{github.base_ref}}" >> $GITHUB_OUTPUT

      - name: UPDATE ECI & RUN UT
        id: run_ut
        shell: bash
        timeout-minutes: 60
        run: |
          set -ex
          rm -rf ./elastic-service
          ln -s /var/lib/elastic-service ./elastic-service
          cd elastic-service && git pull
          ./bin/elastic-ut.sh --pr ${PR_NUMBER} --module fe

#      - name: Clean ECI
#        if: always()
#        run: |
#          echo ${{ steps.run_ut.outputs.ECI_ID }}
#          eci rm ${{ steps.run_ut.outputs.ECI_ID }}

      - name: UT Report
        if: always()
        uses: mikepenz/action-junit-report@v3
        with:
          check_name: 'FE UT Report'
          detailed_summary: true
          token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: ${{ steps.run_ut.outputs.FE_REPORT_DIR }}/*.xml

      - name: Upload log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: FE UT LOG
          path: ${{ steps.run_ut.outputs.RES_LOG }}
          retention-days: 1

      - name: Clean ENV
        if: always()
        run: |
          rm -rf ${{ steps.run_ut.outputs.FE_REPORT_DIR }}
          rm -f ${{ steps.run_ut.outputs.RES_FILE }}
          rm -f ${{ steps.run_ut.outputs.RES_LOG }}
