name: TEST Report
run-name: TEST Report(# ${{ github.event.workflow_run.id }})

on:
  workflow_run:
    workflows: [ "TEST PIPELINE" ]
    types:
      - completed
env:
  PR_NUMBER: ${{ github.event.workflow_run.pull_requests[0].number }}
  BASE_REF: ${{ github.event.workflow_run.pull_requests[0].base.ref }}
  HEAD_SHA: ${{ github.event.workflow_run.head_sha }}
  
permissions:
  checks: write
  actions: write
  contents: write
  deployments: write
  discussions: write
  issues: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  FE-REPORT:
    runs-on: [ self-hosted, quick ]
    steps:
      - name: CLEAN
        run: |
          rm -rf ${{ github.workspace }} && mkdir -p ${{ github.workspace }}

      - name: INFO
        id: info
        run: |
          echo "bucket_prefix=starrocks" >> $GITHUB_OUTPUT

      - name: Download FE UT XML
        id: download-ut-xml
        env:
          bucket_prefix: ${{ steps.info.outputs.bucket_prefix }}
        run: |
          oss_path=oss://${bucket_prefix}-ci-release/main/Release/pr/UT-Report/30544
          size=$(ossutil64 --config-file ~/.ossutilconfig ls ${oss_path}/fe_ut_report.tar.gz | grep "Object Number is" | awk '{print $NF}')
          echo "size=${size}" >> $GITHUB_OUTPUT
          if [[ "$size" != "0" ]]; then
            mkdir fe && cd fe
            ossutil64 --config-file ~/.ossutilconfig cp ${oss_path}/ . --recursive
            tar zxf fe_ut_report.tar.gz
          fi

      - name: Publish UT Report
        uses: mikepenz/action-junit-report@v3
        id: publish_report
        if: steps.download-ut-xml.outputs.size != '0'
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
        with:
          check_name: 'FE UT Report'
          detailed_summary: true
          fail_on_failure: true
          report_paths: ./fe/fe-core/target/surefire-reports/*.xml

      - name: Clean ENV
        if: always()
        run: |
          rm -rf ${{ github.workspace }}/*
