run-name: CI Report - ${{ github.event.workflow_run.pull_requests[0].number }}

on:
  workflow_run:
    workflows: [ "TEST PIPELINE" ]
    types:
      - completed

permissions:
  checks: write
  actions: write
  contents: write
  deployments: write
  discussions: write
  issues: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  INFO:
    runs-on: ubuntu-latest
    steps:
      - name: ECHO
        run: |
          echo ${{ github.event.workflow_run.pull_requests[0].number }}

      - name: Set Workflow Name
        run: echo "::set-env name=WORKFLOW_NAME::Your Workflow - A"

