name: TEST Report
run-name: TEST Report((# ${{ github.event.workflow_run.id }}))

on:
  workflow_run:
    workflows: [ "TEST PIPELINE" ]
    types:
      - completed
env:
  PR_NUMBER: ${{ github.event.workflow_run.pull_requests[0].number }}
  BASE_REF: ${{ github.event.workflow_run.pull_requests[0].base.ref }}
  HEAD_SHA: ${{ github.event.workflow_run.head_sha }}
  
permissions:
  checks: write
  actions: write
  contents: write
  deployments: write
  discussions: write
  issues: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  INFO:
    runs-on: ubuntu-latest
    steps:
      - name: ECHO
        run: |
          echo ${PR_NUMBER}
          echo ${{ env.PR_NUMBER }}
          echo ${BASE_REF}
          echo ${HEAD_SHA}
          echo "${{ toJson(github.event) }}"

      - name: add document label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ env.HEAD_SHA }}
          number: ${{ env.PR_NUMBER }}

