name: hello

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echos ${{ github.event.number }}
      - run: echo a
      - run: echo b

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: sleep 304

