name: HELLO

on:
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.event.number }}
  cancel-in-progress: true

permissions:
  checks: write

env:
  ECI_LIST: C

jobs:
#  prepare:
#    runs-on: ubuntu-latest
#    steps:
#      - echo "" > eci.txt
#
#      - name: 'Upload Artifact'
#        uses: actions/upload-artifact@v3
#        with:
#          name: eci-list
#          path: eci.txt
#          retention-days: 1

  job1:
    runs-on: ubuntu-latest
    name: job1

    steps:
      - name: echos
        id: echos
        run: |
          set -x
          this_var=A
          echos "job1"

      - name: clean
        if: always()
        run: |
          echo ${{steps.echos.outputs.be}}
          echo clean

  job2:
    runs-on: ubuntu-latest
    name: job2
    needs: job1
    if: always() && needs.job1.result == 'success'
    steps:
      - run: |
          echo ${{env.ECI_LIST}}
      - name: sleep 301
        run: |
          set -x
          this_var=B
          echo ECI_LIST=${{env.ECI_LIST}}${this_var} >> $GITHUB_ENV
          echo ECI_LIST=${{ env.ECI_LIST }}${this_var} >> $GITHUB_ENV
          echo "ECI_LIST=${{ env.ECI_LIST }}${this_var}" >> $GITHUB_ENV
#          sleep 101

  job3:
    runs-on: ubuntu-latest
    name: job3
    needs: job2
    steps:
      - name: sleep 302
        run: |
          set -x
          this_var=C
          echo ${{env.ECI_LIST}}
          echo "ECI_LIST=${{env.ECI_LIST}}${this_var}" >> $GITHUB_ENV
          echo job3

  job4:
    runs-on: ubuntu-latest
    name: job4
    needs: job3
    if: always()
    steps:
      - run: |
          echo "clean..."
          echo ${{env.ECI_LIST}}
