name: Test WorkFlow

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
      - pipeline
      - target
  push:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
      - pipeline
      - target

jobs:
#  specific_merge_requested:
#    runs-on: ubuntu-latest
#    if: ${{ github.event.pull_request.merged == true}}
#    steps:
#      - run: echo 'Merged job'
  info:
    runs-on: ubuntu-latest
    steps:
      - name: INFO
        run: |
          echo -e "branch:  ${{ github.head_ref }}\ncommit-id: ${{ github.sha }}\nPR: ${{ github.base_ref }}\n${{ github.run_number }} \n${{ github.run_id }}"

  allocate_fe_ut_resource:
    runs-on: ubuntu-latest
    steps:
      - name: Allocate FE UT Resource
        run: |
          echo "Allocate FE UT Resource!"
  run_fe_ut:
    needs: allocate_fe_ut_resource
    runs-on: ubuntu-latest
    steps:
      - name: RUN FE UT
        run: |
          echo "RUN FE UT!"
  allocate_be_ut_resource:
    runs-on: ubuntu-latest
    steps:
      - name: Allocate BE UT Resource
        run: |
          echo "Allocate BE UT Resource!"
  run_be_ut:
    needs: allocate_be_ut_resource
    runs-on: ubuntu-latest
    steps:
      - name: RUN BE UT
        run: |
          echo "RUN BE UT!"
  be_build:
    runs-on: ubuntu-latest
    needs: [run_fe_ut, run_be_ut]
    steps:
      - name: BE BUILD
        run: |
          echo "be build!"

  fe_build:
    runs-on: ubuntu-latest
    needs: [ run_fe_ut, run_be_ut ]
    steps:
      - name: FE BUILD
        run: |
          echo "fe build!"