name: HELLO

on:
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.event.number }}
  cancel-in-progress: true

permissions:
  checks: write

env:
  ECI_LIST=

jobs:
  job1:
    runs-on: ubuntu-latest
    name: job1

    steps:
      - run: |
          this_var=A
          ECI_LIST=${ECI_LIST},${this_var}
          echo "job1" 

  job2:
    runs-on: ubuntu-latest
    name: job2
    needs: job1
    steps:
      - name: sleep 301
        run: |
          this_var=B
          ECI_LIST=${ECI_LIST},${this_var}
          sleep 301

  job3:
    runs-on: ubuntu-latest
    name: job3
    needs: job2
    if: always()
    steps:
      - run: |
          echo "clean..."
          echo ${ECI_LIST}
