name: MANUAL PIPELINE

on:
  workflow_dispatch:
    inputs:
      IS_REBUILD:
        description: 'REBUILD'
        type: 'boolean'
        default: false

permissions:
  checks: write
  actions: write
  contents: write
  deployments: write
  discussions: write
  issues: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:

  a:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    continue-on-error: true
    name: A
    env:
      BRANCH: 'main'
    strategy:
      fail-fast: false
      matrix:
        build_type: [ Release, ASAN ]
    steps:
      - name: Matrix
        id: matrix_step
        shell: bash
        env:
          build_type: ${{ matrix.build_type }}
        run: |
          echo ${build_type}
          if [[ "${build_type}" == "ASAN" ]]; then
            echo "A=a" >> $GITHUB_OUTPUT
            exit 1
          else
            echo "B=c" >> $GITHUB_OUTPUT
          fi

#      - name: save result
#        id: output
#        if: always()
#        run: |
#          set -x
#          echo "${{steps.matrix_step.outcome}}" > ${{ matrix.build_type }}.txt
#
#      - uses: actions/upload-artifact@v4
#        if: always() && steps.output.outcome == 'success'
#        with:
#          name: BE-UT-RESULT-${{ matrix.build_type }}
#          path: ${{ matrix.build_type }}.txt

  Teardown:
    runs-on: ubuntu-latest
    name: Teardown
    needs: [ a ]
    steps:
      - run: |
          set -x
          echo teardown
          echo '${{ toJSON(needs.a.outputs) }}'


#      - name: Load outputs
#        uses: actions/download-artifact@v4
#        with:
#          path: outputs
#
#      - run: |
#          ls outputs
#          ls outputs/BE-UT-RESULT-ASAN
#          cat outputs/BE-UT-RESULT-ASAN/*.txt
#          cat outputs/BE-UT-RESULT-Release/*.txt
