name: DEPLOY AND SYSTEM TEST PIPELINE

on:
  workflow_call:
    inputs:
      BUILD_TYPE:
        description: 'BUILD TYPE'
        type: 'string'
        default: true


jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: |
          echo ${{ inputs.BUILD_TYPE }}
          sleep 10

      - name: deploy
        run: |
          sleep 10

      - name: deploy
        run: |
          sleep 10

  b:
    runs-on: ubuntu-latest
    needs:
      - a
    steps:
      - name: deploy
        run: |
          echo ${{ inputs.BUILD_TYPE }}
          sleep 10

      - name: deploy
        run: |
          sleep 10

      - name: deploy
        run: |
          sleep 10
          

  c:
    runs-on: ubuntu-latest
    needs:
      - a
    steps:
      - name: deploy
        run: |
          echo ${{ inputs.BUILD_TYPE }}
          sleep 10

      - name: deploy
        run: |
          sleep 10

      - name: deploy
        run: |
          sleep 10

  d:
    runs-on: ubuntu-latest
    needs:
      - b
      - c
    steps:
      - name: deploy
        run: |
          echo ${{ inputs.BUILD_TYPE }}
