name: TEST PIPELINE

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:

  checker:
    runs-on: ubuntu-latest
    name: RUN CHECKER
    steps:
      - name: A
        run: |
          echo "True"
