name: TEST upload

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  checks: write
  actions: write
  contents: write
  deployments: write
  discussions: write
  issues: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  SQL-Tester:
    runs-on: self-hosted
    name: SQL-Tester
    env:
      PR_NUMBER: ${{ github.event.number }}
    steps:
      - run: |
          pwd
          ls
      - name: Clean Workspace
        uses: AutoModality/action-clean@v1.1.0

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: BRANCH INFO
        id: branch
        run: |
          echo ${{github.base_ref}}
          echo "branch=${{github.base_ref}}" >> $GITHUB_OUTPUT

      - name: Checkout PR
        run: |
          BRANCH=${{steps.branch.outputs.branch}}
          git checkout $BRANCH;
          git pull;
          BRANCH_NAME="${BRANCH}-${PR_NUMBER}";
          git fetch origin pull/${PR_NUMBER}/head:${BRANCH_NAME};
          git checkout $BRANCH_NAME;
          git checkout -b merge_pr;
          git merge --squash --no-edit ${BRANCH} || (echo "Merge conflict, please check." && exit -1);

      - name: Run Case

        run: |
          cd ${{ github.workspace }}
          rm -rf ./elastic-service
          ln -s /var/lib/elastic-service ./elastic-service
          cd elastic-service && git pull
          cd ${{ github.workspace }}/test
          cp /var/local/env/nosetests.xml .

#          ./bin/run-sql-tester.sh
#          TODO: output echo "FE: ${{needs.deploy.outputs.fe}}, BE: ${{needs.deploy.outputs.be}}"
      - name: Save event
        id: save_event
        run: |
          set -x
          echo ${GITHUB_EVENT_PATH}
          echo ${GITHUB_EVENT_NAME}
          cat ${GITHUB_EVENT_PATH}
          
          uuid=`uuidgen`
          mkdir -p /var/local/env/event_dir/${uuid}/
          echo "EVENT_DIR=${uuid}" >> $GITHUB_OUTPUT
          cp ${GITHUB_EVENT_PATH} /var/local/env/event_dir/${uuid}/
          cat /var/local/env/event_dir/${uuid}/event.json

      - name: UT Reports
        if: success() || failure()
#        run: |
#          set -x
#          /usr/bin/docker run --label b1cbc5 --workdir /github/workspace --rm -e "PR_NUMBER" -e "INPUT_FILES" \
#          -e "INPUT_EVENT_FILE" -e "INPUT_GITHUB_TOKEN" -e "INPUT_GITHUB_RETRIES" -e "INPUT_COMMIT" \
#          -e "INPUT_CHECK_NAME" -e "INPUT_COMMENT_TITLE" -e "INPUT_COMMENT_MODE" -e "INPUT_FAIL_ON" \
#          -e "INPUT_ACTION_FAIL" -e "INPUT_ACTION_FAIL_ON_INCONCLUSIVE" -e "INPUT_JUNIT_FILES" -e "INPUT_NUNIT_FILES" \
#          -e "INPUT_XUNIT_FILES" -e "INPUT_TRX_FILES" -e "INPUT_TIME_UNIT" -e "INPUT_REPORT_INDIVIDUAL_RUNS" \
#          -e "INPUT_REPORT_SUITE_LOGS" -e "INPUT_DEDUPLICATE_CLASSES_BY_FILE_NAME" -e "INPUT_LARGE_FILES" \
#          -e "INPUT_IGNORE_RUNS" -e "INPUT_JOB_SUMMARY" -e "INPUT_COMPARE_TO_EARLIER_COMMIT" \
#          -e "INPUT_PULL_REQUEST_BUILD" -e "INPUT_EVENT_NAME" -e "INPUT_TEST_CHANGES_LIMIT" \
#          -e "INPUT_CHECK_RUN_ANNOTATIONS" -e "INPUT_CHECK_RUN_ANNOTATIONS_BRANCH" \
#          -e "INPUT_SECONDS_BETWEEN_GITHUB_READS" -e "INPUT_SECONDS_BETWEEN_GITHUB_WRITES" -e "INPUT_JSON_FILE" \
#          -e "INPUT_JSON_THOUSANDS_SEPARATOR" -e "INPUT_JSON_SUITE_DETAILS" -e "INPUT_JSON_TEST_CASE_RESULTS" \
#          -e "INPUT_SEARCH_PULL_REQUESTS" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" \
#          -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" \
#          -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" \
#          -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" \
#          -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" \
#          -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" \
#          -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" \
#          -e GITHUB_EVENT_PATH="/github/workspace/event.json" \
#          -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true \
#          -v "/var/run/docker.sock":"/var/run/docker.sock" \
#          -v "/home/runner/_work/_temp/_github_home":"/github/home" \
#          -v "/home/runner/_work/_temp/_runner_file_commands":"/github/file_commands" \
#          -v "/home/runner/_work/starrocks/starrocks":"/github/workspace" \
#          -v "/home/disk1/nas/event_dir/${{ steps.save_event.outputs.EVENT_DIR }}":"/github/workflow" \
#          ghcr.io/enricomi/publish-unit-test-result-action:v2.6.1
##        uses: EnricoMi/publish-unit-test-result-action@v2.6.1
##        with:
##          files: test/*.xml
##          event_file: /home/disk1/nas/event_dir/${{ steps.save_event.outputs.EVENT_FILE }}
###          files: |
##            test/*.xml
##          junit_files: "test/*.xml"
##          report_suite_logs: "any"
        uses: mikepenz/action-junit-report@v3
        with:
          check_name: 'SQL-Tester Report'
          fail_on_failure: true
          token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: ./test/nosetests.xml
          detailed_summary: false
          job_summary: false
